# Generated by Django 4.1.7 on 2024-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles_images/"
            ),
        ),
    ]
