# Generated by Django 5.0.4 on 2024-05-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_contactinfo_remove_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
